services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: idodidodi/hello-flask:v3.1

    ports:
      - "5000:5000"

    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
