apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: idodidodi/hello-flask:v2.1
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_RUN_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-app-configmap
                  key: FLASK_RUN_PORT
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: APP_ENV
            - name: APP_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: APP_MESSAGE
            - name: APP_VERSION
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: APP_VERSION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
  labels:
    app: flask-app
data:
  FLASK_ENV: production
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5000"
  FLASK_APP: app.py
  APP_MESSAGE: Hello World
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-cronjob
spec:
  schedule: "*/1 * * * *"

  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5

  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl-container
              image: busybox
              command:
                - /bin/sh
                - -c
                - wget -q -O- http://flask-app-service/hello
