apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  DB_PASSWORD: <BASE64_PASSWORD_HERE>
  APP_ENV: <BASE64_ENV_HERE>
  APP_MESSAGE: <BASE64_MESSAGE_HERE>
  APP_VERSION: <BASE64_VERSION_HERE>
