apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
data:
  FLASK_ENV: {{ .Values.config.env }}
  FLASK_RUN_HOST: {{ .Values.config.host }}
  FLASK_RUN_PORT: {{ .Values.service.port | quote }}
  FLASK_APP: app.py
  APP_MESSAGE: {{ .Values.config.message }}
